image: ubuntu:22.04

stages:
  - test


build_cmake:
  before_script:
    - apt-get update -y
    - apt-get upgrade -y
    - apt-get install
      pkg-config
      clang cmake ninja-build
      libsqlite3-dev libcurl4 libcurl3-gnutls libcurl4-openssl-dev libcurlpp-dev
      valgrind -y
  stage: test
  script:
    - mkdir build && cd build
    - cmake ..
    - make -j$(nproc)
